always check for PR to be release

diff --git a/utility/action.yml b/utility/action.yml
--- a/utility/action.yml
+++ b/utility/action.yml
@@ -39,7 +39,6 @@ runs:
 
   # Detect release
   - name: Check if PR is release
-    if: steps.formatted.outputs.ready == 'false'
     id: release-check
     env: 
       GH_TOKEN: ${{ inputs.gh_token }}
@@ -84,5 +83,7 @@ runs:
   # Validate if we should fail this job
   - name: Check if PR is release
     if: steps.add-and-commit.outputs.committed == 'true'
-    run: exit 1
+    run: |
+      echo "Code was formatted in this workflow. Failing workflow."
+      exit 1
     shell: bash
